reconocedor: reconocedor.o
 cc palindromos.c palindromo.o -o palindromos
palindromo.o: palindromo.c
 cc -c palindromo.o
palindromo_tests: palindromo.o
 cc palindromo_tests.c palindromo.o -o palindromo_tests